name: tf_gpu2
dependencies:
  - python=3.11
  - h5py
  - numpy
  - matplotlib
  - ipython
  - scikit-learn
  - pandas
  - scipy
  - seaborn
  - pydot
  - pip

  - pip:
    - wget
    - graphviz
    - hyperas
    - mlxtend
    - gdown
    - opencv-python
    - tensorflow[and-cuda]