name: ML
dependencies:
  - python
  - tensorflow
  - h5py
  - numpy
  - matplotlib
  - ipython
  - scikit-learn
  - pandas
  - scipy
  - seaborn
  - pydot
  - pip

  - pip:
    - wget
    - graphviz
    - hyperas
    - mlxtend
    - gdown
    - opencv-python

